export const votingPolls = [
  {
    title: 'Cucumbers in your tarator',
    description: 'Do you prefer your cucumber sliced or chopped in the tarator',
    image: '/polls-images/tarator.webp',
    optionOne: 'Chopped',
    optionTwo: 'Sliced',
    votesFirstOption: 12,
    votesSecondOption: 9,
  },
  {
    title: 'Cucumbers in your tarator',
    description: 'Do you prefer your cucumber sliced or chopped in the tarator',
    image: '/polls-images/tarator.webp',
    optionOne: 'Chopped',
    optionTwo: 'Sliced',
    votesFirstOption: 12,
    votesSecondOption: 9,
  },
  {
    title: 'Cucumbers in your tarator',
    description: 'Do you prefer your cucumber sliced or chopped in the tarator',
    image: '/polls-images/tarator.webp',
    optionOne: 'Chopped',
    optionTwo: 'Sliced',
    votesFirstOption: 12,
    votesSecondOption: 9,
  },
  {
    title: 'Cucumbers in your tarator',
    description: 'Do you prefer your cucumber sliced or chopped in the tarator',
    image: '/polls-images/tarator.webp',
    optionOne: 'Chopped',
    optionTwo: 'Sliced',
    votesFirstOption: 12,
    votesSecondOption: 9,
  },
]