export const votingPolls = [
  {
    id: 1,
    title: 'Cucumbers in your tarator',
    description: 'Do you prefer your cucumber sliced or chopped in the tarator',
    image: '/polls-images/tarator.webp',
    optionOne: 'Chopped',
    optionTwo: 'Sliced',
    optionOneImage:'',
    optionTwoImage:'',
    votesFirstOption: 12,
    votesSecondOption: 9,
  },
  {
    id: 2,
    title: 'Cucumbers in your tarator',
    description: 'Do you prefer your cucumber sliced or chopped in the tarator',
    image: '/polls-images/tarator.webp',
    optionOne: 'Chopped',
    optionTwo: 'Sliced',
    optionOneImage:'',
    optionTwoImage:'',
    votesFirstOption: 12,
    votesSecondOption: 9,
  },
  {
    id: 3,
    title: 'Cucumbers in your tarator',
    description: 'Do you prefer your cucumber sliced or chopped in the tarator',
    image: '/polls-images/tarator.webp',
    optionOne: 'Chopped',
    optionTwo: 'Sliced',
    optionOneImage:'',
    optionTwoImage:'',
    votesFirstOption: 12,
    votesSecondOption: 9,
  },
  {
    id: 4,
    title: 'Cucumbers in your tarator',
    description: 'Do you prefer your cucumber sliced or chopped in the tarator',
    image: '/polls-images/tarator.webp',
    optionOne: 'Chopped',
    optionTwo: 'Sliced',
    optionOneImage:'',
    optionTwoImage:'',
    votesFirstOption: 12,
    votesSecondOption: 9,
  },
]