-- CreateTable
CREATE TABLE "Poll" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "description" STRING NOT NULL,
    "votes1" INT4 NOT NULL DEFAULT 0,
    "votes2" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "Poll_pkey" PRIMARY KEY ("id")
);
